export enum SocketCode {
  GET_ALL_ROOMS = "GET_ALL_ROOMS",
  POKER_ROOMS_CHANGED = "POKER_ROOMS_CHANGED",
  GET_ROOM = "GET_ROOM",
  USERS = "USERS",
  POKERROOMS = "POKERROOMS",
  ROOM_MESSAGE = "ROOM_MESSAGE",
  JOIN_ROOM_OBSERVER = "JOIN_ROOM_OBSERVER",
  LEAVE_ROOM_OBSERVER = "LEAVE_ROOM_OBSERVER",
  OBSERVER = "OBSERVER",
  ROOM_DATA = "ROOM_DATA",
  JOIN_ROOM = "JOIN_ROOM",
  ROOM_DATA_UPDATE = "ROOM_DATA_UPDATE",
  CHANGE_STREAM_CLOSED = "CHANGE_STREAM_CLOSED",
  CHANGE_STREAM = "CHANGE_STREAM",
  CHANGE_STREAM_STARTED = "CHANGE_STREAM_STARTED",
}

export enum EventCode {
  GET_ALL_ROOMS = "GET_ALL_ROOMS",
  START_GAME = "startGame",
}
