export enum SocketCode {
  GET_ALL_ROOMS = "GET_ALL_ROOMS",
  POKER_ROOMS_CHANGED = "POKER_ROOMS_CHANGED",
  GET_ROOM = "GET_ROOM",
  USERS = "USERS",
  POKERROOMS = "POKERROOMS",
  ROOM_MESSAGE = "ROOM_MESSAGE",
  JOIN_ROOM_OBSERVER = "JOIN_ROOM_OBSERVER",
  LEAVE_ROOM_OBSERVER = "LEAVE_ROOM_OBSERVER",
  OBSERVER = "OBSERVER",
}

export enum EventCode {
  GET_ALL_ROOMS = "GET_ALL_ROOMS",
  START_GAME = "startGame",
}
